### ISSUE TITLE
SkillUpgradeSystem_Window crashes when opening skill list (new project, English program v1.4.1)

### ISSUE THREAD

**Issue by Naridar** [futokoro/RPGMaker#1]
When opening the skill list in a new, default project, the game crashes with an error log. No plugins other than the necessary ones for SkillUpgradeSystem_Window, in this order:

FTKR_SkillExpansion 1.3.3
FTKR_ShowSkillStatus 1.4.2
FTKR_SkillUpgradeSystem_Core 1.4.0
FTKR_SkillUpgradeSystem_Window 1.4.0

Here is the error log:

`TypeError: Cannot read property 'count' of undefined at Window_SepTypeList.Window_Base.setSepSkillStatusParams (file:///D:/Games/RPG/Project2/js/plugins/FTKR_SkillUpgradeSystem_Window.js:864:10)
    at Window_SepTypeList.Window_Base.drawSepSkillStatus (file:///D:/Games/RPG/Project2/js/plugins/FTKR_SEP_ShowSkillStatus.js:1384:21)
    at Window_SepTypeList.drawSkillStatus (file:///D:/Games/RPG/Project2/js/plugins/FTKR_SkillUpgradeSystem_Window.js:1193:10)
    at Window_SepTypeList.drawItem (file:///D:/Games/RPG/Project2/js/plugins/FTKR_SEP_ShowSkillStatus.js:2098:10)
    at Window_SepTypeList.Window_Selectable.drawAllItems (file:///D:/Games/RPG/Project2/js/rpg_windows.js:1250:18)
    at Window_SepTypeList.refresh (file:///D:/Games/RPG/Project2/js/plugins/FTKR_SEP_ShowSkillStatus.js:2134:8)
    at Window_SepTypeList.setSkillId (file:///D:/Games/RPG/Project2/js/plugins/FTKR_SEP_ShowSkillStatus.js:2326:8)
    at Window_SkillList.update (file:///D:/Games/RPG/Project2/js/plugins/FTKR_SEP_ShowSkillStatus.js:1924:54)
    at file:///D:/Games/RPG/Project2/js/rpg_core.js:6523:19
    at Array.forEach (native)`

**Comment by futokoro** [comment]
Thank you for using my plugins.
In order to use them, you need the following work.

Please set FTKR_SkillExpansion.js 's Plugin Parameter ”Make Sep For Each" to 1.

**Comment by Naridar** [comment]
Thank you very much, it works now.
